import './globals.css'
import { Merriweather_Sans } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';

const inter = Merriweather_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return [{locale: 'enUs'}, {locale: 'ptBr'}];
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
}) {

  let messages;
  try {
    messages = (await import(`@src/config/languages/${params.locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
